spring: 
  application:
    name: Recruiting App
  datasource: 
    url: jdbc:mariadb://localhost:3306/bachelor-recruiting?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        globally_quoted_identifiers: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: artdcxx4@gmail.com
    password: txzc umcv haeh mjwt
    from: Recruiting-Bachelor-Project
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mustache:
    check-template-location: false
 
vaadin: 
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,edu.chnu.recruiting

verifaction-token:
  expiration: 1440 # 24 hours
base-url: http://localhost:8080
