spring: 
  application:
    name: Recruiting App
  datasource: 
    url: jdbc:mysql://localhost:3306/bachelor-recruiting?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: artdcxx4@gmail.com
    password: ${GOOGLE_APPLICATION_PASSWORD}
    from: Recruiting-Bachelor-Project
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart: 
      max-file-size: 30MB
      max-request-size: 50MB
  mustache:
    check-template-location: false
 
vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,edu.chnu.recruiting

verifaction-token:
  expiration: 1440 # 24 hours
base-url: http://localhost:8080
